[package]
name = "send_transaction"
version = "0.1.0"
authors = ["Craig <craigwilliams84@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
